### ISSUE TITLE
automatic-clowncar seemingly does not function with Middleman 3.3.11

### ISSUE THREAD

**Issue by blt** [Octo-Labs/middleman-automatic-clowncar#7]
I've just integrated automatic-clowncar into a Middleman 3.3.11 project and find that clowncare'd images 404 in development and cause build failure on when executing 'middleman build'. I have created a small project to reproduce the issue, here: https://github.com/blt/clowncar_report

I've taken care to ensure that clowncar'd photos are in `sources/photos` (https://github.com/blt/clowncar_report/blob/master/config.rb#L62) and have just got the one photo in the project, here: https://github.com/blt/clowncar_report/blob/master/source/index.html.erb#L6

**Comment by jagthedrummer** [comment]
Oh crap! No good. I'll try to take a look at this tomorrow. Thanks for putting together the sample repo. That's a baller move.

**Comment by blt** [comment]
Happy to, and thank you!
