### ISSUE TITLE
middleman 4: updated dependent gems but images still not generating

### ISSUE THREAD

**Issue by jm3** [Octo-Labs/middleman-automatic-clowncar#9]
hi, i was about to submit a PR that updates the out-of-date gem deps to the latest versions, but it looks like there might be some other issues as well:

With the [updated gemspec](https://github.com/jm3/middleman-automatic-clowncar/commit/0b27e0ed56ec8f8b49bc3b8b9bf006307b71f8f1) automatic-clowncar now bundles without errors against Middleman 4, and generates a clowncar SVG tag with the correct paths. But when I run `middleman build`, clowncar isn't generating any of the actual resized images into `source/photos`, so the images themselves are 404.
1. it looks like `:namespace_directory` needs to be an Array, not a bare Regex, so i wrapped my regex in [brackets] to get it working. not sure if that's expected behavior.
2. referencing `app.images_dir` now errors with: _undefined method `images_dir' for #Middleman::Application Did you mean image_tag?_ so i temporarily changed the regex in my fork to `url.sub("/images/",'/')` to see if that would work (it doesn't).
3. should the plugin be configured in both `development` and `build`? if so, the image thumbnails will only be generated upon build, correct?

here is a test repo for you that uses Middleman 4 and bundles my fork of `middleman-automatic-clowncar`, showing the images NOT being generated into build: [jm3/automatic-clowncar-update](https://github.com/jm3/automatic-clowncar-update)

**Comment by jagthedrummer** [comment]
@jm3 sorry for the ridiculously long delay on this. 😬

In case you're still interested, I just merged some changes that gets this extension working for me in middleman v4.
